version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    image: 742465637076.dkr.ecr.eu-west-2.amazonaws.com/constructng-service:latest
  
    links: #Links the listed services to our application so containers can talk to eachother
      - db
    restart: always
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db